import type { ActivityIdea } from './activity-ideas';

export const partyGameIdeas: ActivityIdea[] = [
  {
    id: 'alias-home',
    title: 'Alias at Home',
    emoji: '🗣️',
    vibe: 'Fast + loud',
    groupSize: '4–12',
    summary: 'The HomeKit Alias game — phones as buzzers, TV as scoreboard.',
    howItWorks: [
      'Open /alias on the TV or laptop',
      'Split into teams and set round timer',
      'Explain words without saying them',
      'Track scores across rounds',
    ],
    homekitTieIn: 'Playable now via the Alias game page.',
  },
  {
    id: 'jackbox-style',
    title: 'Jackbox-Style Trivia',
    emoji: '📱',
    vibe: 'Phone-driven + hilarious',
    groupSize: '3–8',
    summary: 'Everyone uses their phone to answer prompts — TV shows the questions.',
    howItWorks: [
      'Host starts a room on the big screen',
      'Players join from their phones',
      'Answer prompts, draw, or vote each round',
      'Lowest score buys snacks next time',
    ],
    homekitTieIn: 'Future party game engine with phone controllers.',
  },
  {
    id: 'draw-guess',
    title: 'Draw & Guess',
    emoji: '🎨',
    vibe: 'Creative + chaotic',
    groupSize: '4–10',
    summary: 'One person draws, everyone else guesses — points for speed and accuracy.',
    howItWorks: [
      'Rotate the drawer each round',
      'Set a 60-second timer',
      'First correct guess gets the most points',
      'Play 8–10 rounds and crown a winner',
    ],
    homekitTieIn: 'On the Games roadmap as Draw & Guess.',
  },
  {
    id: 'would-you-rather',
    title: 'Would You Rather',
    emoji: '🤔',
    vibe: 'Debates + surprises',
    groupSize: '3–12',
    summary: 'Impossible choices, group votes, and argument bonuses.',
    howItWorks: [
      'Read a would-you-rather prompt',
      'Everyone picks A or B secretly',
      'Reveal and debate the choices',
      'Award points for the funniest justification',
    ],
    homekitTieIn: 'On the Games roadmap; great filler between rounds.',
  },
  {
    id: 'hot-takes',
    title: 'Hot Takes',
    emoji: '🔥',
    vibe: 'Spicy + opinionated',
    groupSize: '3–10',
    summary: 'Controversial opinions, group rates them from cold to nuclear.',
    howItWorks: [
      'Each player submits a hot take',
      'Read them one by one',
      'Group rates: mild, warm, hot, nuclear',
      'Most nuclear take wins',
    ],
    homekitTieIn: 'On the Games roadmap as Hot Takes.',
  },
  {
    id: 'charades-plus',
    title: 'Charades+',
    emoji: '🎭',
    vibe: 'Physical + silly',
    groupSize: '4–16',
    summary: 'Classic charades with category rounds and a timer on the big screen.',
    howItWorks: [
      'Pick categories: movies, games, memes',
      'One actor, team guesses within 90 seconds',
      'Pass costs a point',
      'Team with most correct guesses wins',
    ],
    homekitTieIn: 'On the Games roadmap as Charades+.',
  },
];
