import type { ActivityIdea } from './activity-ideas';

export const boardGameIdeas: ActivityIdea[] = [
  {
    id: 'catan-night',
    title: 'Settlers of Catan Night',
    emoji: '🏝️',
    vibe: 'Strategic + trade-heavy',
    groupSize: '3–4',
    summary: 'Classic resource trading with expansions if the group is experienced.',
    howItWorks: [
      'Set up the base board with random tile layout',
      'Explain robber and trading rules for newcomers',
      'Play to 10 victory points',
      'Optional: best-of-three for regulars',
    ],
    homekitTieIn: 'Track wins on a Plans scoreboard later.',
  },
  {
    id: 'codenames-party',
    title: 'Codenames Session',
    emoji: '🕵️',
    vibe: 'Wordplay + teams',
    groupSize: '4–8',
    summary: 'Two teams, one spymaster each, race to find all their words.',
    howItWorks: [
      'Split into two teams',
      'Spymasters give one-word clues',
      'First team to find all agents wins',
      'Rotate spymasters each round',
    ],
    homekitTieIn: 'Codenames-lite is on the Games roadmap.',
  },
  {
    id: 'ticket-to-ride',
    title: 'Ticket to Ride Evening',
    emoji: '🚂',
    vibe: 'Relaxed + route-building',
    groupSize: '2–5',
    summary: 'Build train routes across the map — great gateway game for mixed groups.',
    howItWorks: [
      'Deal destination tickets and train cards',
      'Take turns drawing cards or claiming routes',
      'Reveal tickets at the end for bonus points',
      'Highest score wins',
    ],
    homekitTieIn: 'Save favorite maps to Plans for repeat nights.',
  },
  {
    id: 'pandemic-coop',
    title: 'Pandemic Co-op',
    emoji: '🦠',
    vibe: 'Cooperative + tense',
    groupSize: '2–4',
    summary: 'Work together to cure diseases before outbreaks overwhelm the world.',
    howItWorks: [
      'Each player picks a role with a unique ability',
      'Discuss strategy openly — it is cooperative',
      'Draw infection cards and manage outbreaks',
      'Win by curing all four diseases',
    ],
    homekitTieIn: 'Great for quieter groups; track wins in Plans.',
  },
  {
    id: 'azul-beautiful',
    title: 'Azul Pattern Night',
    emoji: '🟦',
    vibe: 'Beautiful + tactical',
    groupSize: '2–4',
    summary: 'Draft tiles to build the most aesthetic wall — quick to teach, deep to master.',
    howItWorks: [
      'Take turns drafting tiles from factories',
      'Place tiles on your pattern lines',
      'Score for completed rows, columns, and colors',
      'Highest score after 5 rounds wins',
    ],
    homekitTieIn: 'Pairs well with a cozy cooking evening beforehand.',
  },
];
